library(tidyverse)
library(terra)

run_circuitscape <- function(dir = NULL, 
                             version = "4.0.5",
                             data_type = "raster",
                             scenario = "pairwise",
                             use_included_pairs = "False",
                             point_file = "Nodes.tif",
                             habitat_map_is_resistances = "False", 
                             connect_using_avg_resistances = "False",
                             connect_four_neighbors_only = "False",
                             low_memory_mode = "True",
                             parallelize = "False",
                             solver = "cholmod",
                             print_timings = 1,
                             preemptive_memory_release = "False",
                             print_rusages = "False",
                             max_parallel = 0,
                             mask_file = "None",
                             use_mask = "False",
                             set_null_currents_to_nodata = "False",
                             set_focal_node_currents_to_zero = "False",
                             set_null_voltages_to_nodata = "False",
                             compress_grids = "False",
                             write_cur_maps = 1,
                             write_volt_maps = 0,
                             write_cum_cur_map_only = "False",
                             log_transform_maps = "False",
                             write_max_cur_maps = "True",
                             log_level = "INFO",
                             screenprint_log = "False"){

  write_lines(paste(paste0("[Version]\n",
                           "version = ", version),
                    paste0("[Circuitscape mode]",
                           "data_type = ", data_type, "\n",
                           "scenario = ", scenario),
                    paste0("[Options for pairwise and one-to-all and all-to-one modes]\n",
                           "use_included_pairs = ", use_included_pairs, "\n",
                           "point_file = ", paste0(dir, "/Nodes.tif")),
                    paste0("[Habitat raster or graph]\n",
                           "habitat_map_is_resistances = ", habitat_map_is_resistances, "\n",
                           "habitat_file = ", habitat_file),
                    paste0("[Connection scheme for raster habitat data]\n",
                           "connect_using_avg_resistances = ", connect_using_avg_resistances, "\n",
                           "connect_four_neighbors_only = ", connect_four_neighbors_only),
                    paste0("[Calculation options]\n",
                           "low_memory_mode = ", low_memory_mode, "\n",
                           "parallelize = ", parallelize, "\n",
                           "solver = ", solver, "\n",
                           "print_timings = ", print_timings, "\n",
                           "preemptive_memory_release = ", preemptive_memory_release, "\n",
                           "print_rusages = ", print_rusages, "\n",
                           "max_parallel = ", max_parallel),
                    paste0("[Mask File]\n",
                           "mask_file = ", mask_file, "\n",
                           "use_make = ", use_mask),
                    paste0("[Output options]\n",
                           "set_null_currents_to_nodata = ", set_null_currents_to_nodata, "\n",
                           "set_focal_node_currents_to_zero = ", set_focal_node_currents_to_zero, "\n",
                           "set_null_voltages_to_nodata = ", set_null_voltages_to_nodata, "\n",
                           "compress_grids = ", compress_grids, "\n",
                           "write_cur_maps = ", write_cur_maps, "\n",
                           "write_volt_maps = ", write_volt_maps, "\n",
                           "output_file = ", paste0(dir, "/out.out"), "\n",
                           "write_cum_cur_map_only = ", write_cum_cur_map_only, "\n",
                           "log_transform_maps = ", log_transform_maps, "\n",
                           "write_max_cur_maps = ", write_max_cur_maps),
                    paste0("[Logging Options]\n",
                           "log_level = ", log_level, "\n",
                           "log_file = ", paste0(dir, "/out.log"), "\n",
                           "profiler_log_file = ", paste0(dir, "/out_rusages.out"), "\n",
                           "screenprint_log = ", screenprint_log),
                    sep = "\n\n"),
              paste0(dir, "/Circuitscape_Initialization.ini"))
  
  if(JuliaCall::julia_installed_package("Circuitscape") == "nothing"){
    JuliaCall::julia_command('Pkg.add("Circuitscape")')
  }

  JuliaCall::julia_command(paste0("cd(", dir, ")"))
  JuliaCall::julia_command('using Circuitscape')
  JuliaCall::julia_command('compute("Circuitscape_Initialization.ini")')
  
}